accounts/urls.py
"""accounts URL Configuration"""

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^signup/$',
        views.sign_up,
        name='signup'
    ),
    url(
        r'^checkduplication/$',
        views.check_duplication,
        name='check_duplication'
    ),
    url(
        r'^checkvalidation/$',
        views.check_validation,
        name='check_validation'
    ),
    url(
        r'^checkemail/$',
        views.check_email,
        name='check_email',
    ),
    url(
        r'^sendemail/$',
        views.send_email,
        name='send_email'
    ),
    url(
        r'^updateallusers/$',
        views.update_all_users,
        name='update_all_users'
    ),
    url(
        r'^showallusers/$',
        views.show_all_users,
        name='show_all_users'
    ),
]

giza/urls.py
"""Giza URL Configuration"""

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.show_giza,
        name="show giza"
    ),
    url(
        r'^all/$',
        views.show_all_giza,
        name="show all giza"
    ),
    url(
        r'^new/$',
        views.new_giza,
        name='new giza'
    ),
    url(
        r'^new/(?P<email>.*)/$',
        views.new_giza,
        name='new giza with email'
    ),
    url(
        r'^(?P<id>\d+)/edit/$',
        views.edit_giza,
        name='edit giza'
    ),
    url(
        r'^(?P<id>\d+)/delete/$',
        views.delete_giza,
        name='delete giza'
    ),
    url(
        r'^search/(?P<search_type>.*)/(?P<search_word>.*)/$',
        views.search_giza,
        name='search giza'
    )
]

portality/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(
        r'^accounts/login/$',
        'django.contrib.auth.views.login',
        name='login',
        kwargs={'template_name': 'login.html'}
    ),
    url(
        r'^accounts/logout/$',
        'django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': 'login'}
    ),
    url(
        r'^accounts/passwordchange/$',
        'django.contrib.auth.views.password_change',
        name='passwordchange'
    ),
    url(
        r'^accounts/passwordreset/$',
        'django.contrib.auth.views.password_reset',
        name='passwordreset'
    ),
    url(
        r'^podcast/(?P<pod>\w+)/$',
        'core.views.podcast',
        name="podcast"
    ),
    url(r'^', include('issue.urls')),
    url(r'^db/', include('giza.urls', namespace='giza')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api/', include('core.apiurls', namespace='api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
import sys

# from django.conf import settings

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

reload(sys)
sys.setdefaultencoding('utf-8')


class Profile(models.Model):
    """User model extension"""

    user = models.OneToOneField(User)
    point = models.IntegerField(default=1)
    lastcall = models.DateTimeField(auto_now_add=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create signal"""
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """Update signal"""
    if Profile.objects.filter(user=instance):
        instance.profile.save()
    else:
        Profile.objects.create(user=instance)

accounts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    """Edit form for sign up"""

    email = forms.EmailField(label='email', required=True)
    code = forms.CharField(label='code', required=False)

    class Meta:
        """Meta for RegistrationForm"""

        model = User
        fields = {"username", "email", "code"}

accounts/views.py
# -*- coding: utf-8 -*-
from smtplib import SMTPException
import sys

from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.core.signing import TimestampSigner
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.utils import timezone
from django.utils.formats import localize

from .forms import RegistrationForm

reload(sys)
sys.setdefaultencoding('utf-8')


@user_passes_test(lambda u: u.is_superuser)
def update_all_users(self):
    """To create user extension"""
    if False:
        users = User.objects.all()
        userlist = ''
        for user in users:
            userlist += user.username + '<br>'
            user.profile.lastcall = timezone.now() - timezone.timedelta(days=7)
            user.save()
        msg = '%d  명의 회원을 처리했습니다.<br><br>' % users.count()

        return HttpResponse(msg + userlist)
    else:
        return HttpResponse('잘못된 접근입니다.')


@user_passes_test(lambda u: u.is_superuser)
def show_all_users(self):
    """Show all users point and last_login"""
    users = User.objects.all().order_by('-last_login')
    userlist = ''
    for user in users:
        date = localize(user.last_login)
        userlist += user.username + ', %d, %s<br>' % (user.profile.point, date)
    msg = '%d 명의 회원이 있습니다.<br><br>' % users.count()

    return HttpResponse(msg + userlist)


def check_validation(request):
    """Function"""
    username = request.POST.get('username')
    idcheck = User.objects.filter(username__iexact=username).exists()

    code = request.POST.get('code')
    email = request.POST.get('email')
    signer = TimestampSigner()
    msg = ''
    result = False

    try:
        value = signer.unsign(code, max_age=180)
        code_check = value == email

        if idcheck:
            msg = u"이미 존재하는 아이디입니다."
        elif not code_check:
            msg = u"인증코드가 잘못되었습니다."
        else:
            result = True
    except:
        msg = u"인증코드가 잘못되었습니다."

    data = {
        'result': result,
        'msg': msg,
    }

    return JsonResponse(data)


def sign_up(request):
    """Function"""
    if request.method == "POST":
        userform = RegistrationForm(request.POST)
        if userform.is_valid():
            userform.save(commit=False)
            email = userform.cleaned_data['email']
            code = userform.cleaned_data['code']
            signer = TimestampSigner()
            try:
                value = signer.unsign(code, max_age=86400)
                id_check = value == email
                if (id_check):
                    msg = u"가입성공.<br><a href=%s>로그인</a>" % reverse_lazy('login')
                    userform.save()
                else:
                    msg = u"인증코드를 확인해 주세요."
            except:
                msg = u"인증코드를 확인해 주세요.."
        else:
            msg = u"회원가입 오류.<br>아이디를 확인해 주세요."
        return HttpResponse(msg)
    elif request.method == "GET":
        userform = RegistrationForm()

    return render(
        request,
        "accounts/signup.html",
        {
            'userform': userform,
        }
    )


def check_duplication(request):
    """Function"""
    username = request.POST.get('username')
    idcheck = User.objects.filter(username__iexact=username).exists()
    if (idcheck):
        msg = u"이미 존재하는 아이디입니다."
    else:
        msg = u"사용 가능한 아이디입니다."
    data = {
        'idcheck': idcheck,
        'msg': msg,
    }
    return JsonResponse(data)


def check_email(request):
    """Function"""
    email = request.POST.get('email')

    if User.objects.filter(email__iexact=email).exists():
        msg = u"이미 존재하는 이메일 주소입니다. 비밀번호 찾기를 이용해 보세요."
        data = {
            'msg': msg,
        }
        return JsonResponse(data, status=201)

    signer = TimestampSigner()
    value = signer.sign(email)
    subject = u'[노룩뉴스] 회원가입 인증 메일입니다.'
    body = u'인증코드(이메일주소 포함): %s' % value

    try:
        send_mail(subject, body, settings.EMAIL_HOST_USER, [email], fail_silently=False)
        msg = u"인증코드를 이메일로 발송했습니다."
        data = {
            'msg': msg,
        }
        return JsonResponse(data, status=201)
    except SMTPException:
        return JsonResponse({'status': 'false'}, status=400)


@user_passes_test(lambda u: u.is_superuser)
def send_email(request):
    """Function"""
    id_email = request.user.email
    print "sending email to", id_email
    signer = TimestampSigner()
    value = signer.sign(id_email)
    subject = u'[노룩뉴스] 테스트 메일입니다.'
    body = u'인증코드(이메일주소 포함): %s' % value

    try:
        send_mail(subject, body, settings.EMAIL_HOST_USER, [id_email], fail_silently=False)
        return HttpResponse("email sent", status=201)
    except SMTPException:
        return HttpResponse(status=400)

templates/haru/accounts/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}회원가입{% endblock %}
{% block extra_head_content %}
{{ block.super }}
<script src="{% static 'js/jquery-3.1.1.min.js' %}" /></script>
{% endblock %}
{% block content %}

{% if form.errors %}
<p><font color="red">실패</font></p>
{% endif %}

<div id="wrap">
    <div id="contents">
        <h1>회원가입</h1>
        {% if user.is_authenticated %}
            <div class="annotation">
                {{ user }}님 반갑습니다.
            </div>
        {% else %}
            <div class="annotation">
                회원가입을 하시면 기자정보 및 뉴스 추가, 수정 등이 가능합니다.
            </div>
            <form id="signup_form" method="post" action="{% url 'accounts:signup' %}">
            {% csrf_token %}
            <p style="margin-top:40px"></p>
            <div align="center">
                <table class="member">
                <tr>
                    <td align="center" height="30px" bgcolor="#417690" colspan="3"><font color="#F4F382">필수 입력 항목</font></td>
                </tr>
                <tr>
                    <td width="100px">&nbsp;</td>
                    <td width="270px">&nbsp;</td>
                    <td width="30px" rowspan="7">&nbsp;</td>
                </tr>
                <tr>
                    <td class="label">아이디</td>
                    <td><font size="2">{{ userform.username }}</font>
                    <input type="button" value="중복체크" onClick="checkDuplication()">
                    </td>
                </tr>
                <tr>
                    <td class="label">이메일</td>
                    <td height="30px">{{ userform.email }}
                    <input type="button" value="인증" onClick="checkEmail()">
                    </td>
                </tr>
                <tr>
                    <td class="label"><b>인증코드</b></td>
                    <td height="30px">{{ userform.code }}
                    </td>
                </tr>
                <tr>
                    <td class="label">비밀번호</td>
                    <td>{{ userform.password1 }}</td>
                </tr>
                <tr>
                    <td class="label">비밀번호확인</td>
                    <td height="30px">{{ userform.password2 }}</td>
                </tr>
                <tr>
                    <td align="center" valign="center" height="40px" colspan="3"><input type="submit" id="signup" value="회원가입"></td>
                </tr>
                </table>
            </div>
            </form>

            <table width="100%">
            <tr>
                <td align="center">
                <input type="checkbox" id="concent"> 개인정보 취급방침에 동의합니다.
                </td>
            </tr>
            <tr>
                <td><textarea rows="14" style="width:100%; padding:10px" readonly>
노룩뉴스 개인정보 취급방침
정보통신망 이용촉진 등에 관한 법률 등 관련 법률에 의한 개인정보 보호규정 및 정보통신부가 제정한 개인정보지침을 준수하고 있습니다.

1. 개인정보의 수집 및 이용 목적
- 아이디, 비밀번호, 이메일 주소 : 서비스 이용에 따른 사용자 확인, 중복가입 확인 및 부정이용 방지를 위한 목적으로 사용합니다.
- 이용자의 IP Address: 중복 투표 방지 및 통계학적 분석을 위해 사용합니다.

2. 개인정보의 수집 항목
- 필수항목: 아이디, 비밀번호, 이메일 주소
- 자동수집항목: IP Address, 접속 기록, 쿠키 등

3. 개인정보의 보유 및 이용기간
- 아이디, 비밀번호, 이메일 등 가입 회원정보는 탈퇴 시 파기됩니다.
- 게시물 등록 및 투표시 IP Address는 사이트 폐쇄 시까지 보관합니다.</textarea>
                </td>
            </tr>
            </table>
        {% endif %}
    </div> <!--//contents-->

    <div id="footer">
        <div class="footerMenu">
            <ul>
                {{ FOOTER_TAGS|safe }}
            </ul>
        </div>
    </div>

</div> <!-- //wrap -->

<script src="{% static 'js/signup.js' %}" async></script>
{% endblock %}